#!/usr/bin/php
<?php

error_reporting(E_ERROR);

class Crawler
{
    public function codeVerifier(int $length = 32): string
    {
        $randomString = base64_encode(openssl_random_pseudo_bytes($length));
        return strtr(rtrim($randomString, '='), '+/', '-_');
    }

    public function state(): string
    {
        return $this->codeVerifier(16);
    }

    public function codeChallenge(string $codeVerifier): string
    {
        $encoded = base64_encode(hash('sha256', $codeVerifier, true));
        return strtr(rtrim($encoded, '='), '+/', '-_');
    }

    public function httpRequest(string $url, array $params, bool $post = false): string
    {
        $streamContext = [
            'http' => [
                'max_redirects' => 1,
                'ignore_errors' => true, // capture even 4xx/5xx responses
            ],
        ];

        $query = http_build_query($params);
        if ($post) {
            $streamContext['http']['method']  = 'POST';
            $streamContext['http']['header']  = "Content-Type: application/x-www-form-urlencoded\r\n";
            $streamContext['http']['content'] = $query;
        } else {
            $url .= (strpos($url, '?') === false ? '?' : '&') . $query;
        }

        $context  = stream_context_create($streamContext);
        $contents = @file_get_contents($url, false, $context);

        // --- error handling ---
        if ($contents === false) {
            $error = error_get_last();
            throw new \RuntimeException("HTTP request failed: " . ($error['message'] ?? 'unknown error'));
        }

        if (!isset($http_response_header) || !is_array($http_response_header)) {
            throw new \RuntimeException("No response headers received from $url");
        }

        // Check status code
        $statusLine = $http_response_header[0] ?? null;
        if ($statusLine && preg_match('#HTTP/\d+\.\d+\s+(\d+)#', $statusLine, $m)) {
            $statusCode = (int) $m[1];
            if ($statusCode >= 400) {
                throw new \RuntimeException("HTTP error $statusCode received from $url");
            }
        }

        // Handle redirect
        foreach ($http_response_header as $responseHeader) {
            if (stripos($responseHeader, 'Location: ') === 0) {
                return trim(substr($responseHeader, 10));
            }
        }

        return $contents;
    }

    public function parseJwt(string $jwt)
    {
        $exploded = explode('.', $jwt);
        return json_decode(base64_decode($exploded[1]));
    }
}

$crawler = new Crawler();

/**
 * Url to where we have to GET the Auth Code using a code_challenge.
 */
$authorizationUrl = 'http://localhost:8000/authorize';

/**
 * The URL to where we have to POST the code_verifier to get the tokens.
 */
$tokensUrl = 'http://localhost:8000/tokens';

/**
 * The callback URL of the client.
 * In this example, we don't use that functionality.
 */
$redirectUrl = 'http://example.com/callback';

/**
 * The client ID, given by the Auth Provider.
 */
$clientId = '1';

/**
 * The scopes you want to collect.
 * Add `openid` to get an id_token.
 * Provide more scopes to receive additional claims in the `id_token`.
 */
$scopes = 'openid profile email';

/**
 * The state is sent to the auth provider and back.
 * If these states don't match, the provider is calling us directly.
 */
$state = $crawler->state();

/**
 * A verifier string which will be used to create a code_challenge.
 */
$codeVerifier = $crawler->codeVerifier();

/**
 * A hashed code, using the code_verifier to send to the Auth Provider.
 */
$codeChallenge = $crawler->codeChallenge($codeVerifier);

/**
 * Do the authorization request.
 */
$redirectParams = $crawler->httpRequest($authorizationUrl, [
    'client_id' => (string) $clientId,
    'redirect_uri' => $redirectUrl,
    'response_type' => 'code',
    'scope' => $scopes,
    'state' => $state,
    'code_challenge' => $codeChallenge,
    'code_challenge_method' => 'S256',
]);

if (!$redirectParams) {
    throw new Exception('No redirect received!');
}

/**
 * We expect a redirect URL after requesting the auth code.
 * 1. We should verify the $_GET['state'] with our $state
 * 2. We should post back the $_GET['code'] and our code_verifier
 */
$callbackComponents = parse_url($redirectParams);
parse_str($callbackComponents['query'], $callbackQuery);

if (!$code = $callbackQuery['code']) {
    throw new Exception('Code not found!');
}

if (!$receivedState = $callbackQuery['state']) {
    throw new Exception('State not found!');
}

if ($state !== $receivedState) {
    throw new Exception('States do not match!');
}

/**
 * Now we can post the $_GET['code'] to request the tokens.
 */
$content = $crawler->httpRequest($tokensUrl, [
    'grant_type' => 'authorization_code',
    'client_id' => (string) $clientId,
    'redirect_uri' => $redirectUrl,
    'code_verifier' => $codeVerifier,
    'code' => $code,
], true);

if (!$content) {
    throw new Exception('No token response received');
}

$content = json_decode($content, true);
if (!$content) {
    throw new Exception('No valid json received');
}

$dump = array_merge($content, [
    'parsed_access_token' => $crawler->parseJwt($content['access_token']),
]);

if (isset($content['id_token'])) {
    $dump['parsed_id_token'] = $crawler->parseJwt($content['id_token']);
}

print_r($dump);
